import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Headertop from "./components/header/header";
import HeaderMobile from "./components/header-mobile";
import Footer from "./components/header/footer";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-raleway)' }}
      >
         <Headertop/>
          <HeaderMobile/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
